### ISSUE TITLE
length of input audio

### ISSUE THREAD

**Issue by winner96** [JusperLee/UtterancePIT-Speech-Separation#5]
hi. I couldn't get wsj0 dataset.

I'm using other datasets and trying to fit to this model.

i wants to know if the length of input audio should be equal.

thanks :)

**Comment by JusperLee** [comment]
4s  8khz audio == 32000

**Comment by winner96** [comment]
Thanks. i'm trying to work with AVSPEECH set. trimmed as 16khz 5s == 80000frames. (11000 wav files per speaker.)
valid set MSE does not decrease under 20.
However, paper shows that it easily decrease under 5.
Is this problem of my dataset?

plz let me know what was your final MSE Loss

thanks :)

**Comment by JusperLee** [comment]
I have not used the AVSPEECH dataset. I can only give you the log file of wsj0-2mix.

Kai
[train.log](https://github.com/JusperLee/UtterancePIT-Speech-Separation/files/5610798/train.log)

**Comment by winner96** [comment]
@JusperLee 

This is what I wanted :)

Thanks a lot.
